### ISSUE TITLE
[rust] recommend https://github.com/Centril/rust-safe annotations for unsafe code?

### ISSUE THREAD

**Issue by g-k** [mozilla-services/websec-check#17]
For the rust guidelines, we have  `- [ ] If you must use 'unsafe', include a comment explaining why you believe its use is sound and its behavior is correct and well defined` and there's a crate for that now: https://github.com/Centril/rust-safe#getting-started

So pending some basic review of that crate, we could change that item to "include a [rust-safe](https://github.com/Centril/rust-safe) annotation with a reason or comment explaining why you believe its use is sound and its behavior is correct and well defined" 

Thoughts @psiinon?

@bbangert I believe you originally recommended adding the comments for unsafe code have you tried `rust-safe`?

**Comment by bbangert** [comment]
I have not tried it, so I don't have any meaningful input on that. Maybe @pjenvey or Donovan (I don't know his github handle) have more input.
