### ISSUE TITLE
[rust] review and update rust recommendations

### ISSUE THREAD

**Issue by g-k** [mozilla-services/websec-check#28]
From the push service RRA with @jrconlin, @pjenvey, @tublitzed, @Mcat12, we might want to update our rust tool and version recommendations:

* use a rust stable release a few releases back old

Depending on their experience recommend tools from:

* cargo-sweep https://crates.io/crates/cargo-sweep (clean up build files)
* cargo-geiger https://crates.io/crates/cargo-geiger (track unsafe code usage)
* cargo-guppy https://github.com/facebookincubator/cargo-guppy (many things: dep graph analysis and policy enforcement)

**Comment by AzureMarker** [comment]
[`cargo-crev`] was the crate I was thinking of when I said `cargo-geiger`, but the latter is probably even more appropriate.

[`cargo-crev`]: https://crates.io/crates/cargo-crev

**Comment by g-k** [comment]
Found out about https://lib.rs/crates/cargo-dephell recently too though I'm not crazy about giving it a GH PAT (scoped to public read only might be fine).
